### ISSUE TITLE
name_glob namedata_t val

### ISSUE THREAD

**Issue by LuisSchaefer** [Steve2955/turtle-graphics-compiler#10]
@Steve2955 

Folgender Ausschnitt für das Hinzufügen von Variablen- und Funktionsnamen an die Namenstabelle:
```c
		if (type == name_glob) {
			//das ist Quatsch.. muss der Wert sein, der nach dem "=" kommt -> eigentlich ja IMMER übernächstes Token, oder?
			namedata_t d_name_entry;
			d_name_entry.val = atof(tok);
			name_entry->d = d_name_entry;
		}
```

Wie unschwer an meinem Kommentar zu erkennen ist die aktuelle Positionierung des Codes bzw. das, was eingelesen wird Qutasch (wäre der Variablen- oder Funktionsname). Wir wollen den Wert, der nach Initialisierung der globalen Variable, festgelegt wird.

Wie wollen wir den Wert einlesen? Ist das IMMER der übernächste Token der Wert, den wir wollen? mMn ja, aber vielleicht vergesse ich einen wichtigen Fall.
Ist an dieser Stelle (also generell im Lexer) die richtige Position, um den Wert einzulesen?

Gesamter Code in lsch-lex

**Comment by Steve2955** [comment]
Der Lexer soll den Namenseinträgen keinen Wert zuweisen. Es soll lediglich der Eintrag erstellt werden, der dann später vom Parser genutzt wird.

**Comment by LuisSchaefer** [comment]
Macht der Parser
